name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mfinelli/setup-shfmt@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq bats
      - name: ShellCheck
        run: shellcheck -x auto-approve.sh smart-approve.sh auto-learn.sh
      - name: Tests
        run: bats test/
